name = "cloudflare-hono-drizzle-zod-starter-pack"
compatibility_date = "2025-01-25"
main = "src/index.ts"
minify = true
send_metrics = false
compatibility_flags = [ "nodejs_compat" ]


[observability.logs]
enabled = true

[vars]
JWT_SECRET = "super-secret-jwt-key"
[[d1_databases]]
binding = "DB"
database_name = "dodo-shoes-db"
database_id = "00636dd2-ac1f-417e-bc2a-1a5d0d3e16d1"
migrations_dir = "drizzle"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
