// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/10/2026, 3:00:44 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/adham-atya/DODO_SHOES/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/adham-atya/DODO_SHOES/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/adham-atya/DODO_SHOES/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/adham-atya/DODO_SHOES/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/adham-atya/DODO_SHOES/frontend/plugins/**/*.{js,ts,mjs}","/home/adham-atya/DODO_SHOES/frontend/composables/**/*.{js,ts,mjs}","/home/adham-atya/DODO_SHOES/frontend/utils/**/*.{js,ts,mjs}","/home/adham-atya/DODO_SHOES/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/adham-atya/DODO_SHOES/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/adham-atya/DODO_SHOES/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/adham-atya/DODO_SHOES/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;